// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $loans from "./routes/loans.tsx";
import * as $login from "./routes/login.tsx";
import * as $members from "./routes/members.tsx";
import * as $reports from "./routes/reports.tsx";
import * as $savings from "./routes/savings.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $DashboardContent from "./islands/DashboardContent.tsx";
import * as $DashboardStats from "./islands/DashboardStats.tsx";
import * as $LandingCTA from "./islands/LandingCTA.tsx";
import * as $LandingFeatures from "./islands/LandingFeatures.tsx";
import * as $LandingHero from "./islands/LandingHero.tsx";
import * as $LandingStats from "./islands/LandingStats.tsx";
import * as $LandingTestimonials from "./islands/LandingTestimonials.tsx";
import * as $LoansTable from "./islands/LoansTable.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MemberForm from "./islands/MemberForm.tsx";
import * as $MembersTable from "./islands/MembersTable.tsx";
import * as $NavbarActions from "./islands/NavbarActions.tsx";
import * as $ReportsContent from "./islands/ReportsContent.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/loans.tsx": $loans,
    "./routes/login.tsx": $login,
    "./routes/members.tsx": $members,
    "./routes/reports.tsx": $reports,
    "./routes/savings.tsx": $savings,
    "./routes/settings.tsx": $settings,
  },
  islands: {
    "./islands/DashboardContent.tsx": $DashboardContent,
    "./islands/DashboardStats.tsx": $DashboardStats,
    "./islands/LandingCTA.tsx": $LandingCTA,
    "./islands/LandingFeatures.tsx": $LandingFeatures,
    "./islands/LandingHero.tsx": $LandingHero,
    "./islands/LandingStats.tsx": $LandingStats,
    "./islands/LandingTestimonials.tsx": $LandingTestimonials,
    "./islands/LoansTable.tsx": $LoansTable,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MemberForm.tsx": $MemberForm,
    "./islands/MembersTable.tsx": $MembersTable,
    "./islands/NavbarActions.tsx": $NavbarActions,
    "./islands/ReportsContent.tsx": $ReportsContent,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
